### ISSUE TITLE
Playlist shuffling

### ISSUE THREAD

**Issue by Vexed01** [Drapersniper/Audio#3]
Playlists appear to not shuffle the first few tracks when loaded. In this example is a 100 song Spotify playlist. The first (currently playing) and second are the same all three times. The first song (currently playing) is also the first song listed on Spotify.

Whilst the first 1 (or 2) songs not shuffling isn't a dealbreaker, it gives the _impression_ that shuffling overall does not work.

![https://vex.s-ul.eu/tD5JGHjJ](https://vex.s-ul.eu/tD5JGHjJ)

![https://vex.s-ul.eu/0GNWQzVn](https://vex.s-ul.eu/0GNWQzVn)

![https://vex.s-ul.eu/WIWNrZ16](https://vex.s-ul.eu/WIWNrZ16)

**Comment by Drapersniper** [comment]
Ahh hmmm after looking into it it appears to be by design, the first song in the queue isn't shuffled

when using `search`, `playlist start` and other enqueue commands.

the idea here was to not unexpectedly change the "playing next" track when enqueuing something new, but it had the negative consequence of not shuffling the first song on an empty queue enqueue.

For now I've fixed this by ensuring the queue is always shuffled, let me know how it works out.
