### ISSUE TITLE
"Play from message" context menu command queueing duplicate tracks

### ISSUE THREAD

**Issue by karlsbjorn** [Drapersniper/Audio#306]
**Describe the bug**
When queueing a YouTube track from a message using the right-click context menu command, the same track can end up getting queued twice due to the link creating an embed.

**To Reproduce**
1. Send a message with a single youtube link
2. Right click "Play from message"
3. Bot puts two tracks in queue

**Expected behavior**
The bot puts one track in queue

**Additional context**
This eval can be used to check which links would get queued when invoking the context menu command (same code as in the command itself):
```py
from pylav.extension.red.utils.validators import valid_query_attachment
import shlex
from pylav.constants.regex import SOURCE_INPUT_MATCH_MERGED
message = await channel.fetch_message(YOUR_MESSAGE_ID_HERE)
content = message.content.strip()
for embed in message.embeds:
    if embed.description:
        content += f" {embed.description}"
    if embed.title:
        content += f" {embed.title}"
    if embed.url and valid_query_attachment(embed.url):
        content += f" {embed.url}"
    if embed.footer:
        if embed.footer.text:
            content += f" {embed.footer.text}"
        if embed.footer.icon_url:
            content += f" {embed.footer.icon_url}"
    if hasattr(embed, "video") and embed.video and embed.video.url:
        content += f" {embed.video.url}"
    for field in embed.fields:
        if field.value:
            content += f" {field.value}"
        if field.name:
            content += f" {field.name}"
valid_matches = set()
for part in shlex.split(content):
    part = part.strip()
    for __ in SOURCE_INPUT_MATCH_MERGED.finditer(part):
        valid_matches.add(part)
return valid_matches
```
For example:
![image](https://user-images.githubusercontent.com/40699625/226121689-c068f475-63f0-4e2c-a698-d3cfa79b75eb.png)

**Comment by Drapersniper** [comment]
Wanted to get your opinion on how to fix this, we have a few options all with cons.

1 - Ignore embeds, this would be the simplest fix, but messages with embeds can no longer be used in this case (think other bot messages etc)
2 - Ignore duplicate tracks on the same message - what if someone genuinely wants to enqueue the same track multiple times?, then again it wouldn't be foolproof because if the URL is genuinely different it wouldn't do anything i.e the eval you showed.
3 - Ignore **youtube** (and maybe spotify) embedded players - unsure of repercussions there may be and what may stop working if this is done.
players -unsure of repercussions there may be and what may stop working if this is done.
4 - ??? open to suggestions

**Comment by karlsbjorn** [comment]
How about: If there's a match in message content, ignore embeds. If not, then look at embeds if there are any?

**Comment by Drapersniper** [comment]
> How about: If there's a match in message content, ignore embeds. If not, then look at embeds if there are any?

That breaks a core aspect of "play from message" which is allowing multiple matches across *all* of the message (attachments included), while i see why you suggested it, i think that would/could be confusing, i don't particularly like conditional behaviours like this, imo its either a all or nothing scenario otherwise it wont be clear to the user when it is supposed to work.

**Comment by karlsbjorn** [comment]
Not sure what the best approach would be then. My use case for it is much simpler than that
Someone posts a single link, then someone right clicks to play it. Nothing more to it.
I see your point though

**Comment by Drapersniper** [comment]
wont be fixing it immediately, i have a bunch of changes pending locally with some upstream changes for lavalink - but will introduce *some* fix for it when i push those changes.

I'll probably go with 3

for the time being tell your users to post a link with `<url>` this should disable the embedded afaik
